image: node:10.14.1


 pipelines:
      production:
       - step:
           script:
             - npm install
             - npm run build
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git