image: node:10.14.1


 pipelines:
     staging:
       - step:
           caches:
             - node
           script:
             - npm install
             - npm run build
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING.git staging:dev
     
     production:
       - step:
           caches:
             - node
           script:
             - npm install
             - npm run build
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git production:dev